EAD_workspace/4_semestre/06.Fiap.Web.MVC/Fiap06.Wbe.MVC/Fiap06.Wbe.MVC/Models/Animal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Fiap06.Wbe.MVC.Models
{
    [Table("TAnimal")]
    public class Animal
    {

        // nao preciso colocar a anotacao Key pq ele ja entende que eh uma chave se o nome do meu
        // atributo for Id ou ClasseId.
        [Column("Id")]
        public int AnimalId { get; set; }

        [Required]
        [MaxLength(100)]
        public string Nome { get; set; }


        public string Raca { get; set; }

        public bool Castrado { get; set; }

        public float Peso { get; set; }

    }

}

EAD_workspace/4_semestre/06.Fiap.Web.MVC/Fiap06.Wbe.MVC/Fiap06.Wbe.MVC/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap06.Wbe.MVC.Models
{
    public class Produto
    {

        public int ProdutoId { get; set; }

        public string Nome { get; set; }

    }

}

EAD_workspace/4_semestre/06.Fiap.Web.MVC/Fiap06.Wbe.MVC/Fiap06.Wbe.MVC/Controllers/AnimalController.cs
using Fiap06.Wbe.MVC.Models;
using Fiap06.Wbe.MVC.Persistencia;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap06.Wbe.MVC.Controllers
{
    public class AnimalController : Controller
    {

        private PetshopContext _context = new PetshopContext();

        // GET: Animal
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Animal animal)
        {

            _context.Animais.Add(animal);
            _context.SaveChanges();
            TempData["msg"] = "Animal cadastrado com sucesso!";
            return RedirectToAction("Cadastrar");
        }

        [HttpGet]
        public ActionResult Listar()
        {
            List<Animal> animais = _context.Animais.ToList();
            return View(animais);
        }

        [HttpGet]
        public ActionResult Alterar(int id)
        {
            //buscar o animal no banco de dados
            var animal = _context.Animais.Find(id);
            //retorna a pagina com os dados do animal
            return View(animal);
        }

        [HttpPost]
        public ActionResult Alterar(Animal animal)
        {
            _context.Entry(animal).State = EntityState.Modified;
            _context.SaveChanges();

            TempData["msg"] = "Animal editado com sucesso!";
            return RedirectToAction("Listar");
        }
    
        [HttpPost]
        public ActionResult Remover(int codigo)
        {
            _context.Animais.Remove(_context.Animais.Find(codigo));
            _context.SaveChanges();
            TempData["msg"] = "Animal excluído com sucesso";
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult Pesquisar(string nome)
        {

            List<Animal> animais = _context.Animais.Where(a => a.Nome.Contains(nome) || a.Raca.Contains(nome)).ToList();
            return View("Listar", animais);
        }

    }

}

EAD_workspace/4_semestre/06.Fiap.Web.MVC/Fiap06.Wbe.MVC/Fiap06.Wbe.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap06.Wbe.MVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

EAD_workspace/4_semestre/06.Fiap.Web.MVC/Fiap06.Wbe.MVC/Fiap06.Wbe.MVC/Views/Animal/Alterar.cshtml
@model Fiap06.Wbe.MVC.Models.Animal

@{
    ViewBag.Title = "Alterar";
}

<h2>Alterar</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(a => a.AnimalId)
    <div class="form-group">
        @Html.LabelFor(a => a.Nome)
        @Html.TextBoxFor(a => a.Nome, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(a => a.Raca)
        @Html.TextBoxFor(a => a.Raca, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(a => a.Peso)
        @Html.TextBoxFor(a => a.Peso, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.CheckBoxFor(a => a.Castrado)
        @Html.LabelFor(a => a.Castrado)
    </div>

    <input type="submit" value="EDITAR" class="btn btn-primary" />

}

EAD_workspace/4_semestre/06.Fiap.Web.MVC/Fiap06.Wbe.MVC/Fiap06.Wbe.MVC/Views/Animal/Cadastrar.cshtml
@model Fiap06.Wbe.MVC.Models.Animal

@{
                /**/

                ViewBag.Title = "Cadastrar Animal";
}

<h2>Cadastrar Animal</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>@TempData["msg"]</strong>
    </div>
}

@using (Html.BeginForm())
{

    <div class="form-group">
        @Html.LabelFor(animal => animal.Nome)
        @Html.TextBoxFor(animal => animal.Nome, new { @class = "form-control", placeholder = "digite o nome do animal" })
    </div>

    <div class="form-group">
        @Html.LabelFor(animal => animal.Peso)
        @Html.TextBoxFor(animal => animal.Peso, new { @class = "form-control", placeholder = "Digite o peso do animal" })
    </div>

    <div class="form-group">
        @Html.LabelFor(animal => animal.Raca)
        @Html.TextBoxFor(animal => animal.Raca, new { @class = "form-control", placeholder = "digite a raça" })
    </div>

    <div class="form-group">
        @Html.CheckBoxFor(animal => animal.Castrado)
        @Html.LabelFor(animal => animal.Castrado)
    </div>
    <div>
        <input type="submit" value="CADASTRAR" class="btn btn-default" />
    </div>

 

}

EAD_workspace/4_semestre/06.Fiap.Web.MVC/Fiap06.Wbe.MVC/Fiap06.Wbe.MVC/Views/Animal/Listar.cshtml
@model List<Fiap06.Wbe.MVC.Models.Animal>

@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>


@if (TempData["msg"] != null)
{
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>@TempData["msg"]</strong>
    </div>
}

@using (Html.BeginForm("Pesquisar", "Animal", FormMethod.Get, new {@class = "form-inline" }))
{
    @Html.TextBox("Nome", null, new {@class = "form-control", placeholder="Digite um nome"})
    <input type="submit" value="Pesquisar" class="btn btn-default btn-md"/>
}

<table class="table table-striped">

    <thead>
        <tr>
            <th>ID</th>
            <th>NOME</th>
            <th>RAÇA</th>
            <th>CASTRADO</th>
            <th>PESO</th>
            <th>AÇÕES</th>
        </tr>
    </thead>

    @foreach (var animal in Model)
    {

        <tr>
            <td>@animal.AnimalId</td>
            <td>@animal.Nome</td>
            <td>@animal.Raca</td>
            <td>@(animal.Castrado ? "Sim" : "Não")</td>
            <td>@animal.Peso</td>
            <td>
                @Html.ActionLink(" ", "Alterar", new { id = animal.AnimalId }, new { @class = "glyphicon glyphicon-pencil" })
                <a onclick="idExcluir.value = @animal.AnimalId" data-toggle="modal" data-target="#myModal" href="">
                    <span class="glyphicon glyphicon-trash"></span>
                </a>
            </td>
        </tr>

    }

</table>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Excluir</h4>
            </div>
            <div class="modal-body">
                Deseja realmente excluir o animal selecionado?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Remover", "Animal"))
                {
                    <input type="hidden" id="idExcluir" name="codigo" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-default" >Excluir</button>
                }
            </div>
        </div>
    </div>
</div>