EAD_workspace/4_semestre/JogosOnline/JogosOnline/Models/Genero.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace JogosOnline.Models
{
    public class Genero
    {

        public int GeneroId { get; set; }
        public string Nome { get; set; }
        public IList<Jogo> Jogos { get; set; }

    }

}

EAD_workspace/4_semestre/JogosOnline/JogosOnline/Models/Jogo.cs
using System;

namespace JogosOnline.Models
{
    public class Jogo
    {

        public int JogoId { get; set; }
        public string Nome { get; set; }
        public DateTime DataLancamento { get; set; }
        public Plataforma? Plataforma { get; set; }
        public bool Disponivel { get; set; }
        public Genero Genero { get; set; }
        public int GeneroId { get; set; }

    }
}

EAD_workspace/4_semestre/JogosOnline/JogosOnline/Models/Plataforma.cs
namespace JogosOnline.Models
{
    public enum Plataforma
    {

        Playstation, Supernes, Nitendo, Atari, Xbox

    }
}

EAD_workspace/4_semestre/JogosOnline/JogosOnline/ViewModels/JogoViewModel.cs
using JogosOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JogosOnline.ViewModels
{
    public class JogoViewModel
    {

        public Jogo Jogo { get; set; }
        public SelectList Generos { get; set; }
        public IList<Jogo> ListaJogos { get; set; }

    }

}

EAD_workspace/4_semestre/JogosOnline/JogosOnline/Controllers/GeneroController.cs
using JogosOnline.Models;
using JogosOnline.UnitsOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JogosOnline.Controllers
{
    public class GeneroController : Controller
    {

        private UnitOfWork _unit = new UnitOfWork();

        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Genero genero)
        {

            try
            {
                _unit.GeneroRepository.Cadastrar(genero);
                _unit.Save();
                TempData["msg"] = "Genero cadastrado com sucesso!";
            } catch
            {
                TempData["msg"] = "Erro ao tentar cadastrar o gênero!";
            }
            
            return RedirectToAction("Cadastrar");
        }

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }

    }

}

EAD_workspace/4_semestre/JogosOnline/JogosOnline/Controllers/JogoController.cs
using JogosOnline.Models;
using JogosOnline.UnitsOfWork;
using JogosOnline.ViewModels;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JogosOnline.Controllers
{
    public class JogoController : Controller
    {

        private UnitOfWork _unit = new UnitOfWork();

        public ActionResult Cadastrar()
        {
            JogoViewModel viewModel = new JogoViewModel();
            viewModel.Generos = new SelectList(_unit.GeneroRepository.Listar(), "GeneroId", "Nome");
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Cadastrar(JogoViewModel viewModel)
        {

            viewModel.Jogo.Disponivel = false;

            try
            {
                _unit.JogoRepository.Cadastrar(viewModel.Jogo);
                _unit.Save();
                TempData["msg"] = "Jogo cadastrado com sucesso!";
            } catch
            {
                TempData["msg"] = "Erro ao tentar cadastrar o jogo!";
            }

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult Listar()
        {
            
            var jogos = _unit.JogoRepository.Listar();
            carregarComboGeneros();

            return View(jogos);
        }

        [HttpGet]
        public ActionResult Atualizar(int codigo)
        {
            JogoViewModel viewModel = new JogoViewModel();
            viewModel.Jogo = _unit.JogoRepository.Buscar(codigo);
            viewModel.Generos = new SelectList(_unit.GeneroRepository.Listar(), "GeneroId", "Nome");

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Atualizar(JogoViewModel viewModel)
        {

            try
            {
                _unit.JogoRepository.Atualizar(viewModel.Jogo);
                _unit.Save();
                TempData["msg"] = "Jogo editado com sucesso!";
            } catch
            {
                TempData["msg"] = "Erro ao tentar editar o jogo!";
            }
            return RedirectToAction("Listar");
        }

        [HttpPost]
        public ActionResult Remover(int codigo)
        {

            try
            {
                _unit.JogoRepository.Remover(codigo);
                _unit.Save();
                TempData["msg"] = "Jogo excluído com sucesso!";
            } catch
            {
                TempData["msg"] = "Erro ao tentar excluir o jogo!";
            }

            return RedirectToAction("Listar");
        }

        [HttpPost]
        public ActionResult Disponibilizar(int codigo)
        {

            var jogo = _unit.JogoRepository.Buscar(codigo);
            jogo.Disponivel = true;

            try
            {
                _unit.JogoRepository.Atualizar(jogo);
                _unit.Save();
                TempData["msg"] = "Jogo disponibilizado!";
            } catch
            {
                TempData["msg"] = "Erro ao tentar disponibilizar o jogo!";
            }

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult PesquisarPorNome(string nome)
        {

            var jogos = _unit.JogoRepository.ListarPor(j => j.Nome.Contains(nome));
            carregarComboGeneros();

            return View("Listar", jogos);
        }

        [HttpGet]
        public ActionResult PesquisarPorGenero(int? id)
        {

            IList<Jogo> jogos = null;
            if (id == null)
            {
                jogos = _unit.JogoRepository.Listar();
            } else
            {
                jogos = _unit.JogoRepository.ListarPor(j => j.GeneroId == id);
            }

            carregarComboGeneros();

            return View("Listar", jogos);
        }

        private void carregarComboGeneros()
        {
            ViewBag.Generos = new SelectList(_unit.GeneroRepository.Listar(), "GeneroId", "Nome");
        }

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }

    }

}

EAD_workspace/4_semestre/JogosOnline/JogosOnline/Views/Jogo/Atualizar.cshtml
@model JogosOnline.ViewModels.JogoViewModel

@{
    ViewBag.Title = "Atualizar Jogo";
}

<h2>Atualizar Jogo</h2>

@using (Html.BeginForm())
{

    @Html.HiddenFor(j => j.Jogo.JogoId)

    <div class="form-group">
        @Html.LabelFor(j => j.Jogo.Nome)
        @Html.TextBoxFor(j => j.Jogo.Nome, new {@class = "form-control", placeholder = "Nome do jogo"})
    </div>

    <div class="form-group">
        @Html.LabelFor(j => j.Jogo.DataLancamento)
        @Html.TextBoxFor(j => j.Jogo.DataLancamento, new {@class = "form-control", placeholder = "dd/mm/yyyy" })
    </div>

    <div class="form-group">
        @Html.LabelFor(j => j.Jogo.Plataforma)
        @Html.EnumDropDownListFor(j => j.Jogo.Plataforma, "Selecione", new {@class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(j => j.Jogo.Genero)
        @Html.DropDownListFor(j => j.Jogo.GeneroId, Model.Generos, new {@class = "form-control" })
    </div>

    @MyHelper.CriarSubmit("Editar", "btn btn-primary")
    @Html.ActionLink("Cancelar", "Listar", "Jogo", new {@class = "btn btn-danger" })

}

EAD_workspace/4_semestre/JogosOnline/JogosOnline/Views/Jogo/Cadastrar.cshtml
@model JogosOnline.ViewModels.JogoViewModel


@{
    ViewBag.Title = "Cadastrar Jogo";
}

<h2>Cadastrar Jogo</h2>

@using (Html.BeginForm())
{

    <div class="form-group">
        @Html.LabelFor(j => j.Jogo.Nome)
        @Html.TextBoxFor(j => j.Jogo.Nome, new {@class = "form-control", placeholder = "Nome do jogo" })
    </div>

    <div class="form-group">
        @Html.LabelFor(j => j.Jogo.DataLancamento)
        @Html.TextBoxFor(j => j.Jogo.DataLancamento, new {@class = "form-control", placeholder = "dd/mm/aaaa" })
    </div>

    <div class="form-group">
        @Html.LabelFor(j => j.Jogo.Plataforma)
        @Html.EnumDropDownListFor(j => j.Jogo.Plataforma, "Selecione", new {@class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(j => j.Jogo.Genero)
        @Html.DropDownListFor(j => j.Jogo.GeneroId, Model.Generos, "Selecione", new {@class = "form-control" })
    </div>

    @MyHelper.CriarSubmit("Cadastrar", "btn btn-primary")

}

EAD_workspace/4_semestre/JogosOnline/JogosOnline/Views/Jogo/Listar.cshtml
@model List<JogosOnline.Models.Jogo>


@{
    ViewBag.Title = "Listar Jogos";
}

<h2>Listar Jogos</h2>

@if (TempData["msg"] != null)
{
    @MyHelper.Message(@TempData["msg"].ToString())
}


<div class="row">
    <div class="col-md-5">
        @using (Html.BeginForm("PesquisarPorNome", "Jogo", FormMethod.Get, new { @class = "form-inline" }))
        {

            <input name="nome" type="text" class="form-control" placeholder="Digite o nome" />
            @MyHelper.CriarSubmit("Pesquisar por Nome", "btn btn-default")

        }
    </div>
    <div class="col-md-5">
        @using (Html.BeginForm("PesquisarPorGenero", "Jogo", FormMethod.Get, new { @class = "form-inline" }))
        {
            @Html.DropDownList("id", ViewBag.Generos as SelectList, "Selecione", new { @class = "form-control" })
            @MyHelper.CriarSubmit("Pesquisar por Genero", "btn btn-default")

        }
    </div>
</div>

    <table class="table table-hover">

        <thead>
        <th>Nome</th>
        <th>Data Lançamento</th>
        <th>Plataforma</th>
        <th>Gênero</th>
        <th>Disponível</th>
        <th>Ações</th>
        </thead>

        <tbody>

            @foreach (var jogo in Model)
            {
                <tr>
                    <td>@jogo.Nome</td>
                    <td>@jogo.DataLancamento.ToShortDateString()</td>
                    <td>@jogo.Plataforma</td>
                    <td>@jogo.Genero.Nome</td>
                    <td>@(jogo.Disponivel ? "Sim" : "Não")</td>
                    <td>
                        @if (!jogo.Disponivel)
                        {
                            @Html.ActionLink("Editar", "Atualizar", new { @codigo = jogo.JogoId }, new { @class = "btn btn-primary btn-sm" })
                            <button onclick="excluirCodigo.value = @jogo.JogoId" type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modalExcluir">
                                Excluir
                            </button>
                            <button onclick="disponivelCodigo.value = @jogo.JogoId" type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#modalDisponibilizar">
                                Disponibilizar
                            </button>
                        }
                    </td>
                </tr>
            }

        </tbody>

    </table>


    <!-- Modal Excluir-->
    <div class="modal fade" id="modalExcluir" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Confirmação</h4>
                </div>
                <div class="modal-body">
                    Deseja realmente excluir o jogo selecionado?
                </div>
                <div class="modal-footer">
                    @using (Html.BeginForm("Remover", "Jogo"))
                    {
                        <input type="hidden" name="codigo" id="excluirCodigo" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">Não</button>
                        <button type="submit" class="btn btn-danger">Sim</button>
                    }
                </div>
            </div>
        </div>
    </div>

    <!-- Modal Disponibilizar -->
    <div class="modal fade" id="modalDisponibilizar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Confirmação</h4>
                </div>
                <div class="modal-body">
                    Deseja realmente disponibilizar o jogo selecionado?
                </div>
                <div class="modal-footer">
                    @using (Html.BeginForm("Disponibilizar", "Jogo"))
                    {
                        <input type="hidden" name="codigo" id="disponivelCodigo" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">Não</button>
                        <button type="submit" class="btn btn-success">Sim</button>
                    }
                </div>
            </div>
        </div>
    </div>

EAD_workspace/4_semestre/JogosOnline/JogosOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Jogos Online", "Cadastrar", "Genero", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Genero<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastrar Genero", "Cadastrar", "Genero")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Jogos<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastrar Jogo", "Cadastrar", "Jogo")</li>
                            <li>@Html.ActionLink("Listar Jogos", "Listar", "Jogo")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>